/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;

export const idlService = IDL.Service({
  'getContacts' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'subject' : IDL.Text,
            'name' : IDL.Text,
            'email' : IDL.Text,
            'message' : IDL.Text,
            'phone' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getDownloads' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'title' : IDL.Text,
            'description' : IDL.Text,
            'category' : IDL.Text,
            'fileUrl' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getNotifications' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'title' : IDL.Text,
            'date' : Time,
            'message' : IDL.Text,
            'category' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getVillageInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'area' : IDL.Float64,
          'district' : IDL.Text,
          'state' : IDL.Text,
          'villageName' : IDL.Text,
          'wards' : IDL.Nat,
          'population' : IDL.Nat,
          'households' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  
  return IDL.Service({
    'getContacts' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'subject' : IDL.Text,
              'name' : IDL.Text,
              'email' : IDL.Text,
              'message' : IDL.Text,
              'phone' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getDownloads' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'title' : IDL.Text,
              'description' : IDL.Text,
              'category' : IDL.Text,
              'fileUrl' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getNotifications' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'title' : IDL.Text,
              'date' : Time,
              'message' : IDL.Text,
              'category' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getVillageInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'area' : IDL.Float64,
            'district' : IDL.Text,
            'state' : IDL.Text,
            'villageName' : IDL.Text,
            'wards' : IDL.Nat,
            'population' : IDL.Nat,
            'households' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };